<?php
function dbConnect($usertype, $connectionType = 'mysqli') {
    $host = 'localhost';
    $db = 'phpsols';
    if ($usertype  == 'read') {
        $user = 'psread';
        //$pwd = 'K1yoMizu^dera';
        $pwd = 'read';
    } elseif ($usertype == 'write') {
        $user = 'pswrite';
        //$pwd = '0Ch@Nom1$u';
        $pwd = 'write';
    } else {
        exit('Unrecognized user');
    }
    if ($connectionType == 'mysqli') {
        // @ Error Control Operator: https://www.php.net/manual/en/language.operators.errorcontrol.php
        // any error messages that might be generated by that expression will be ignored
        $conn = @ new mysqli($host, $user, $pwd, $db);
        if ($conn->connect_error) {
            exit($conn->connect_error);
        }
        return $conn;
    } else {
        try {
            return new PDO("mysql:host=$host;dbname=$db", $user, $pwd);
        } catch (PDOException $e) {
            echo $e->getMessage();
        }
    }
}
