<?php
/*
 * https://github.com/PHPMailer/PHPMailer/blob/master/examples/mail.phps
 *
 * PHPMailer Guide
 * https://blog.mailtrap.io/phpmailer/
 * test PHP mail functionality, we will use Mailtrap, a fake SMTP server
 */

//Import the PHPMailer class into the global namespace
use PHPMailer\PHPMailer\PHPMailer;

require_once __DIR__ . '/vendor/autoload.php';

// create a new PHPMailer object
$mail = new PHPMailer();

// SMTP configuration
$mail->isSMTP();
$mail->Host = 'smtp.mailtrap.io';
$mail->SMTPAuth = true;
// You must put the appropriate username and password
$mail->Username = 'xxxxxxxxxxxxxx'; //paste one generated by Mailtrap
$mail->Password = 'yyyyyyyyyyyyyy'; //paste one generated by Mailtrap

$mail->SMTPSecure = 'tls';
$mail->Port = 2525;

// Specify PHPMailer headers
$mail->setFrom('info@mailtrap.io', 'Mailtrap');
$mail->addReplyTo('info@mailtrap.io', 'Mailtrap');
$mail->addAddress('destino@loquesea.com', 'Sr. Destino');

//Set the subject line
$mail->Subject = 'PHPMailer mail() test';

// Read an HTML message body from an external file, convert referenced images to embedded,
// convert HTML into a basic plain-text alternative body
$mail->msgHTML(file_get_contents('contents.html'), __DIR__);

//Replace the plain text body with one created manually
$mail->AltBody = 'This is a plain-text message body';

//Attach an image file
$mail->addAttachment('images/phpmailer_mini.png');

//send the message, check for errors
if (!$mail->send()) {
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message sent!';
}
