<!DOCTYPE html>
<html lang="en">
<head>
    <title>Book-O-Rama Book Entry Results</title>
</head>
<body>
<h1>Book-O-Rama Book Entry Results</h1>
<?php

if (!isset($_POST['ISBN']) || !isset($_POST['Author'])
    || !isset($_POST['Title']) || !isset($_POST['Price'])) {
    echo "<p>You have not entered all the required details.<br />
             Please go back and try again.</p>";
    exit;
}

// create short variable names
$isbn = $_POST['ISBN'];
$author = $_POST['Author'];
$title = $_POST['Title'];
$price = $_POST['Price'];
// doubleval — Alias of floatval(). floatval — Get float value of a variable
// https://www.php.net/manual/en/function.floatval.php
$price = doubleval($price);

// https://www.php.net/manual/en/language.operators.errorcontrol.php
// Error control operator: the at sign (@). When prepended to an expression in PHP,
// any error messages that might be generated by that expression will be ignored.
@$db = new mysqli('localhost', 'bookorama', 'bookorama123', 'books');

if (mysqli_connect_errno()) {
    echo "<p>Error: Could not connect to database.<br/>
             Please try again later.</p>";
    exit;
}

$query = "INSERT INTO Books VALUES (?, ?, ?, ?)";
$stmt = $db->prepare($query);
// https://www.php.net/manual/en/mysqli-stmt.bind-param
// s corresponding variable has type string
// d corresponding variable has type double
$stmt->bind_param('sssd', $isbn, $author, $title, $price);
$stmt->execute();

if ($stmt->affected_rows > 0) {
    echo "<p>Book inserted into the database.</p>";
} else {
    echo "<p>An error has occurred.<br/>
              The item was not added.</p>";
}

$db->close();
?>
</body>
</html>
